export interface CountryInfo {
    iso: string;
    currency: string;
    name: string;
    flag: string;
}

export const COUNTRY_CURRENCY_MAP: Record<string, { currency: string; name: string; flag: string }> = {
    AF: { currency: 'AFN', name: 'Afghanistan', flag: '🇦🇫' }, AL: { currency: 'ALL', name: 'Albania', flag: '🇦🇱' }, DZ: { currency: 'DZD', name: 'Algeria', flag: '🇩🇿' },
    AD: { currency: 'EUR', name: 'Andorra', flag: '🇦🇩' }, AO: { currency: 'AOA', name: 'Angola', flag: '🇦🇴' }, AG: { currency: 'XCD', name: 'Antigua & Barbuda', flag: '🇦🇬' },
    AR: { currency: 'ARS', name: 'Argentina', flag: '🇦🇷' }, AM: { currency: 'AMD', name: 'Armenia', flag: '🇦🇲' }, AU: { currency: 'AUD', name: 'Australia', flag: '🇦🇺' },
    AT: { currency: 'EUR', name: 'Austria', flag: '🇦🇹' }, AZ: { currency: 'AZN', name: 'Azerbaijan', flag: '🇦🇿' }, BS: { currency: 'BSD', name: 'Bahamas', flag: '🇧🇸' },
    BH: { currency: 'BHD', name: 'Bahrain', flag: '🇧🇭' }, BD: { currency: 'BDT', name: 'Bangladesh', flag: '🇧🇩' }, BB: { currency: 'BBD', name: 'Barbados', flag: '🇧🇧' },
    BY: { currency: 'BYN', name: 'Belarus', flag: '🇧🇾' }, BE: { currency: 'EUR', name: 'Belgium', flag: '🇧🇪' }, BZ: { currency: 'BZD', name: 'Belize', flag: '🇧🇿' },
    BJ: { currency: 'XOF', name: 'Benin', flag: '🇧🇯' }, BT: { currency: 'BTN', name: 'Bhutan', flag: '🇧🇹' }, BO: { currency: 'BOB', name: 'Bolivia', flag: '🇧🇴' },
    BA: { currency: 'BAM', name: 'Bosnia & Herzegovina', flag: '🇧🇦' }, BW: { currency: 'BWP', name: 'Botswana', flag: '🇧🇼' }, BR: { currency: 'BRL', name: 'Brazil', flag: '🇧🇷' },
    BN: { currency: 'BND', name: 'Brunei', flag: '🇧🇳' }, BG: { currency: 'BGN', name: 'Bulgaria', flag: '🇧🇬' }, BF: { currency: 'XOF', name: 'Burkina Faso', flag: '🇧🇫' },
    BI: { currency: 'BIF', name: 'Burundi', flag: '🇧🇮' }, CV: { currency: 'CVE', name: 'Cabo Verde', flag: '🇨🇻' }, KH: { currency: 'KHR', name: 'Cambodia', flag: '🇰🇭' },
    CM: { currency: 'XAF', name: 'Cameroon', flag: '🇨🇲' }, CA: { currency: 'CAD', name: 'Canada', flag: '🇨🇦' }, CF: { currency: 'XAF', name: 'Central African Rep.', flag: '🇨🇫' },
    TD: { currency: 'XAF', name: 'Chad', flag: '🇹🇩' }, CL: { currency: 'CLP', name: 'Chile', flag: '🇨🇱' }, CN: { currency: 'CNY', name: 'China', flag: '🇨🇳' },
    CO: { currency: 'COP', name: 'Colombia', flag: '🇨🇴' }, KM: { currency: 'KMF', name: 'Comoros', flag: '🇰🇲' }, CD: { currency: 'CDF', name: 'Congo (DR)', flag: '🇨🇩' },
    CG: { currency: 'XAF', name: 'Congo (Rep.)', flag: '🇨🇬' }, CR: { currency: 'CRC', name: 'Costa Rica', flag: '🇨🇷' }, HR: { currency: 'EUR', name: 'Croatia', flag: '🇭🇷' },
    CU: { currency: 'CUP', name: 'Cuba', flag: '🇨🇺' }, CY: { currency: 'EUR', name: 'Cyprus', flag: '🇨🇾' }, CZ: { currency: 'CZK', name: 'Czech Republic', flag: '🇨🇿' },
    DK: { currency: 'DKK', name: 'Denmark', flag: '🇩🇰' }, DJ: { currency: 'DJF', name: 'Djibouti', flag: '🇩🇯' }, DM: { currency: 'XCD', name: 'Dominica', flag: '🇩🇲' },
    DO: { currency: 'DOP', name: 'Dominican Republic', flag: '🇩🇴' }, TL: { currency: 'USD', name: 'East Timor', flag: '🇹🇱' }, EC: { currency: 'USD', name: 'Ecuador', flag: '🇪🇨' },
    EG: { currency: 'EGP', name: 'Egypt', flag: '🇪🇬' }, SV: { currency: 'USD', name: 'El Salvador', flag: '🇸🇻' }, GQ: { currency: 'XAF', name: 'Equatorial Guinea', flag: '🇬🇶' },
    ER: { currency: 'ERN', name: 'Eritrea', flag: '🇪🇷' }, EE: { currency: 'EUR', name: 'Estonia', flag: '🇪🇪' }, SZ: { currency: 'SZL', name: 'Eswatini', flag: '🇸🇿' },
    ET: { currency: 'ETB', name: 'Ethiopia', flag: '🇪🇹' }, FJ: { currency: 'FJD', name: 'Fiji', flag: '🇫🇯' }, FI: { currency: 'EUR', name: 'Finland', flag: '🇫🇮' },
    FR: { currency: 'EUR', name: 'France', flag: '🇫🇷' }, GA: { currency: 'XAF', name: 'Gabon', flag: '🇬🇦' }, GM: { currency: 'GMD', name: 'Gambia', flag: '🇬🇲' },
    GE: { currency: 'GEL', name: 'Georgia', flag: '🇬🇪' }, DE: { currency: 'EUR', name: 'Germany', flag: '🇩🇪' }, GH: { currency: 'GHS', name: 'Ghana', flag: '🇬🇭' },
    GR: { currency: 'EUR', name: 'Greece', flag: '🇬🇷' }, GD: { currency: 'XCD', name: 'Grenada', flag: '🇬🇩' }, GT: { currency: 'GTQ', name: 'Guatemala', flag: '🇬🇹' },
    GN: { currency: 'GNF', name: 'Guinea', flag: '🇬🇳' }, GW: { currency: 'XOF', name: 'Guinea-Bissau', flag: '🇬🇼' }, GY: { currency: 'GYD', name: 'Guyana', flag: '🇬🇾' },
    HT: { currency: 'HTG', name: 'Haiti', flag: '🇭🇹' }, HN: { currency: 'HNL', name: 'Honduras', flag: '🇭🇳' }, HU: { currency: 'HUF', name: 'Hungary', flag: '🇭🇺' },
    IS: { currency: 'ISK', name: 'Iceland', flag: '🇮🇸' }, IN: { currency: 'INR', name: 'India', flag: '🇮🇳' }, ID: { currency: 'IDR', name: 'Indonesia', flag: '🇮🇩' },
    IR: { currency: 'IRR', name: 'Iran', flag: '🇮🇷' }, IQ: { currency: 'IQD', name: 'Iraq', flag: '🇮🇶' }, IE: { currency: 'EUR', name: 'Ireland', flag: '🇮🇪' },
    IL: { currency: 'ILS', name: 'Israel', flag: '🇮🇱' }, IT: { currency: 'EUR', name: 'Italy', flag: '🇮🇹' }, JM: { currency: 'JMD', name: 'Jamaica', flag: '🇯🇲' },
    JP: { currency: 'JPY', name: 'Japan', flag: '🇯🇵' }, JO: { currency: 'JOD', name: 'Jordan', flag: '🇯🇴' }, KZ: { currency: 'KZT', name: 'Kazakhstan', flag: '🇰🇿' },
    KE: { currency: 'KES', name: 'Kenya', flag: '🇰🇪' }, KI: { currency: 'AUD', name: 'Kiribati', flag: '🇰🇮' }, KW: { currency: 'KWD', name: 'Kuwait', flag: '🇰🇼' },
    KG: { currency: 'KGS', name: 'Kyrgyzstan', flag: '🇰🇬' }, LA: { currency: 'LAK', name: 'Laos', flag: '🇱🇦' }, LV: { currency: 'EUR', name: 'Latvia', flag: '🇱🇻' },
    LB: { currency: 'LBP', name: 'Lebanon', flag: '🇱🇧' }, LS: { currency: 'LSL', name: 'Lesotho', flag: '🇱🇸' }, LR: { currency: 'LRD', name: 'Liberia', flag: '🇱🇷' },
    LY: { currency: 'LYD', name: 'Libya', flag: '🇱🇾' }, LI: { currency: 'CHF', name: 'Liechtenstein', flag: '🇱🇮' }, LT: { currency: 'EUR', name: 'Lithuania', flag: '🇱🇹' },
    LU: { currency: 'EUR', name: 'Luxembourg', flag: '🇱🇺' }, MG: { currency: 'MGA', name: 'Madagascar', flag: '🇲🇬' }, MW: { currency: 'MWK', name: 'Malawi', flag: '🇲🇼' },
    MY: { currency: 'MYR', name: 'Malaysia', flag: '🇲🇾' }, MV: { currency: 'MVR', name: 'Maldives', flag: '🇲🇻' }, ML: { currency: 'XOF', name: 'Mali', flag: '🇲🇱' },
    MT: { currency: 'EUR', name: 'Malta', flag: '🇲🇹' }, MH: { currency: 'USD', name: 'Marshall Islands', flag: '🇲🇭' }, MR: { currency: 'MRU', name: 'Mauritania', flag: '🇲🇷' },
    MU: { currency: 'MUR', name: 'Mauritius', flag: '🇲🇺' }, MX: { currency: 'MXN', name: 'Mexico', flag: '🇲🇽' }, FM: { currency: 'USD', name: 'Micronesia', flag: '🇫🇲' },
    MD: { currency: 'MDL', name: 'Moldova', flag: '🇲🇩' }, MC: { currency: 'EUR', name: 'Monaco', flag: '🇲🇨' }, MN: { currency: 'MNT', name: 'Mongolia', flag: '🇲🇳' },
    ME: { currency: 'EUR', name: 'Montenegro', flag: '🇲🇪' }, MA: { currency: 'MAD', name: 'Morocco', flag: '🇲🇦' }, MZ: { currency: 'MZN', name: 'Mozambique', flag: '🇲🇿' },
    MM: { currency: 'MMK', name: 'Myanmar', flag: '🇲🇲' }, NA: { currency: 'NAD', name: 'Namibia', flag: '🇳🇦' }, NR: { currency: 'AUD', name: 'Nauru', flag: '🇳🇷' },
    NP: { currency: 'NPR', name: 'Nepal', flag: '🇳🇵' }, NL: { currency: 'EUR', name: 'Netherlands', flag: '🇳🇱' }, NZ: { currency: 'NZD', name: 'New Zealand', flag: '🇳🇿' },
    NI: { currency: 'NIO', name: 'Nicaragua', flag: '🇳🇮' }, NE: { currency: 'XOF', name: 'Niger', flag: '🇳🇪' }, NG: { currency: 'NGN', name: 'Nigeria', flag: '🇳🇬' },
    KP: { currency: 'KPW', name: 'North Korea', flag: '🇰🇵' }, MK: { currency: 'MKD', name: 'North Macedonia', flag: '🇲🇰' }, NO: { currency: 'NOK', name: 'Norway', flag: '🇳🇴' },
    OM: { currency: 'OMR', name: 'Oman', flag: '🇴🇲' }, PK: { currency: 'PKR', name: 'Pakistan', flag: '🇵🇰' }, PW: { currency: 'USD', name: 'Palau', flag: '🇵🇼' },
    PS: { currency: 'ILS', name: 'Palestine', flag: '🇵🇸' }, PA: { currency: 'PAB', name: 'Panama', flag: '🇵🇦' }, PG: { currency: 'PGK', name: 'Papua New Guinea', flag: '🇵🇬' },
    PY: { currency: 'PYG', name: 'Paraguay', flag: '🇵🇾' }, PE: { currency: 'PEN', name: 'Peru', flag: '🇵🇪' }, PH: { currency: 'PHP', name: 'Philippines', flag: '🇵🇭' },
    PL: { currency: 'PLN', name: 'Poland', flag: '🇵🇱' }, PT: { currency: 'EUR', name: 'Portugal', flag: '🇵🇹' }, QA: { currency: 'QAR', name: 'Qatar', flag: '🇶🇦' },
    RO: { currency: 'RON', name: 'Romania', flag: '🇷🇴' }, RU: { currency: 'RUB', name: 'Russia', flag: '🇷🇺' }, RW: { currency: 'RWF', name: 'Rwanda', flag: '🇷🇼' },
    KN: { currency: 'XCD', name: 'Saint Kitts & Nevis', flag: '🇰🇳' }, LC: { currency: 'XCD', name: 'Saint Lucia', flag: '🇱🇨' }, VC: { currency: 'XCD', name: 'Saint Vincent', flag: '🇻🇨' },
    WS: { currency: 'WST', name: 'Samoa', flag: '🇼🇸' }, SM: { currency: 'EUR', name: 'San Marino', flag: '🇸🇲' }, ST: { currency: 'STN', name: 'Sao Tome & Principe', flag: '🇸🇹' },
    SA: { currency: 'SAR', name: 'Saudi Arabia', flag: '🇸🇦' }, SN: { currency: 'XOF', name: 'Senegal', flag: '🇸🇳' }, RS: { currency: 'RSD', name: 'Serbia', flag: '🇷🇸' },
    SC: { currency: 'SCR', name: 'Seychelles', flag: '🇸🇨' }, SL: { currency: 'SLL', name: 'Sierra Leone', flag: '🇸🇱' }, SG: { currency: 'SGD', name: 'Singapore', flag: '🇸🇬' },
    SK: { currency: 'EUR', name: 'Slovakia', flag: '🇸🇰' }, SI: { currency: 'EUR', name: 'Slovenia', flag: '🇸🇮' }, SB: { currency: 'SBD', name: 'Solomon Islands', flag: '🇸🇧' },
    SO: { currency: 'SOS', name: 'Somalia', flag: '🇸🇴' }, ZA: { currency: 'ZAR', name: 'South Africa', flag: '🇿🇦' }, KR: { currency: 'KRW', name: 'South Korea', flag: '🇰🇷' },
    SS: { currency: 'SSP', name: 'South Sudan', flag: '🇸🇸' }, ES: { currency: 'EUR', name: 'Spain', flag: '🇪🇸' }, LK: { currency: 'LKR', name: 'Sri Lanka', flag: '🇱🇰' },
    SD: { currency: 'SDG', name: 'Sudan', flag: '🇸🇩' }, SR: { currency: 'SRD', name: 'Suriname', flag: '🇸🇷' }, SE: { currency: 'SEK', name: 'Sweden', flag: '🇸🇪' },
    CH: { currency: 'CHF', name: 'Switzerland', flag: '🇨🇭' }, SY: { currency: 'SYP', name: 'Syria', flag: '🇸🇾' }, TW: { currency: 'TWD', name: 'Taiwan', flag: '🇹🇼' },
    TJ: { currency: 'TJS', name: 'Tajikistan', flag: '🇹🇯' }, TZ: { currency: 'TZS', name: 'Tanzania', flag: '🇹🇿' }, TH: { currency: 'THB', name: 'Thailand', flag: '🇹🇭' },
    TG: { currency: 'XOF', name: 'Togo', flag: '🇹🇬' }, TO: { currency: 'TOP', name: 'Tonga', flag: '🇹🇴' }, TT: { currency: 'TTD', name: 'Trinidad & Tobago', flag: '🇹🇹' },
    TN: { currency: 'TND', name: 'Tunisia', flag: '🇹🇳' }, TR: { currency: 'TRY', name: 'Turkey', flag: '🇹🇷' }, TM: { currency: 'TMT', name: 'Turkmenistan', flag: '🇹🇲' },
    TV: { currency: 'AUD', name: 'Tuvalu', flag: '🇹🇻' }, UG: { currency: 'UGX', name: 'Uganda', flag: '🇺🇬' }, UA: { currency: 'UAH', name: 'Ukraine', flag: '🇺🇦' },
    AE: { currency: 'AED', name: 'United Arab Emirates', flag: '🇦🇪' }, GB: { currency: 'GBP', name: 'United Kingdom', flag: '🇬🇧' }, US: { currency: 'USD', name: 'United States', flag: '🇺🇸' },
    UY: { currency: 'UYU', name: 'Uruguay', flag: '🇺🇾' }, UZ: { currency: 'UZS', name: 'Uzbekistan', flag: '🇺🇿' }, VU: { currency: 'VUV', name: 'Vanuatu', flag: '🇻🇺' },
    VE: { currency: 'VES', name: 'Venezuela', flag: '🇻🇪' }, VN: { currency: 'VND', name: 'Vietnam', flag: '🇻🇳' }, YE: { currency: 'YER', name: 'Yemen', flag: '🇾🇪' },
    ZM: { currency: 'ZMW', name: 'Zambia', flag: '🇿🇲' }, ZW: { currency: 'USD', name: 'Zimbabwe', flag: '🇿🇼' },
};

export const ALL_COUNTRIES: CountryInfo[] = Object.entries(COUNTRY_CURRENCY_MAP)
    .map(([iso, v]) => ({ iso, ...v }))
    .sort((a, b) => a.name.localeCompare(b.name));
